#!/usr/bin/ruby
#
# You have an array of numbers.
# Identify the number(s) that appear an odd number of times.
#

a = [ 10, 10, 20, 20, 20, 30, 30, 9, 9, 8, 8, 7, 7, 6, 6, 4, 4, 4 ]

def get_num(n, *a)
  count = 0
  for i in a
    if n == i
      count += 1
    end
  end
  return count
end

wanted = []
for i in a.uniq
  n = get_num(i, *a)
  if n % 2 != 0
    wanted << i
  end
end

puts wanted
  
